// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module packet_filtering (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        from_eth_V_dout,
        from_eth_V_empty_n,
        from_eth_V_read,
        to_shell_V_din,
        to_shell_V_full_n,
        to_shell_V_write,
        to_pr_V_din,
        to_pr_V_full_n,
        to_pr_V_write,
        src_mac_addr_V,
        debug_bit_V
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [72:0] from_eth_V_dout;
input   from_eth_V_empty_n;
output   from_eth_V_read;
output  [72:0] to_shell_V_din;
input   to_shell_V_full_n;
output   to_shell_V_write;
output  [72:0] to_pr_V_din;
input   to_pr_V_full_n;
output   to_pr_V_write;
input  [47:0] src_mac_addr_V;
input  [0:0] debug_bit_V;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg from_eth_V_read;
reg[72:0] to_shell_V_din;
reg to_shell_V_write;
reg[72:0] to_pr_V_din;
reg to_pr_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [3:0] state_V_load_load_fu_252_p1;
wire   [0:0] grp_nbreadreq_fu_130_p3;
reg    ap_predicate_op13_read_state1;
reg    ap_predicate_op29_read_state1;
reg    ap_predicate_op44_read_state1;
reg    ap_predicate_op61_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [3:0] state_V_load_reg_550;
reg   [0:0] tmp_3_reg_566;
reg    ap_predicate_op89_write_state2;
reg   [0:0] tmp_2_reg_570;
reg    ap_predicate_op94_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [3:0] state_V;
reg   [63:0] first_packet_org_dat;
reg   [0:0] first_packet_org_las;
reg   [7:0] first_packet_org_tke;
reg   [63:0] first_packet_in_data;
reg   [63:0] second_packet_org_da;
reg   [0:0] second_packet_org_la;
reg   [7:0] second_packet_org_tk;
reg   [0:0] app_packet_out_last_s;
reg    from_eth_V_blk_n;
wire    ap_block_pp0_stage0;
reg    to_shell_V_blk_n;
reg    to_pr_V_blk_n;
reg   [72:0] reg_242;
reg   [7:0] reg_248;
reg   [0:0] tmp_last_V_reg_554;
reg   [0:0] tmp_last_V_1_reg_560;
reg   [0:0] tmp_1_reg_574;
wire   [63:0] lhs_V_1_fu_328_p1;
reg   [63:0] lhs_V_1_reg_578;
reg   [0:0] tmp_reg_583;
wire   [63:0] lhs_V_fu_386_p1;
reg   [63:0] lhs_V_reg_587;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_app_packet_out_last_3_phi_fu_161_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_app_packet_out_last_3_reg_158;
reg   [0:0] ap_phi_mux_app_packet_out_last_2_phi_fu_170_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_app_packet_out_last_2_reg_167;
reg    ap_block_pp0_stage0_01001;
wire   [72:0] tmp_7_fu_488_p4;
wire   [72:0] tmp_6_fu_498_p4;
wire   [72:0] tmp_37_fu_508_p4;
wire   [72:0] tmp_21_fu_518_p4;
wire   [3:0] storemerge_cast_cast_fu_276_p3;
wire   [3:0] storemerge1_cast_cas_fu_302_p3;
wire   [3:0] storemerge3_cast_cas_fu_372_p3;
wire   [63:0] x_V_fu_440_p9;
wire   [15:0] tmp_20_fu_342_p1;
wire   [7:0] tmp_17_fu_338_p1;
wire   [7:0] grp_fu_212_p4;
wire   [7:0] grp_fu_222_p4;
wire   [7:0] grp_fu_232_p4;
wire   [47:0] observedAddress_V_fu_346_p6;
wire   [0:0] tmp_s_fu_360_p2;
wire   [0:0] tmp_22_fu_366_p2;
wire   [7:0] tmp_8_fu_396_p1;
wire   [7:0] tmp_11_fu_410_p4;
wire   [7:0] tmp_14_fu_430_p4;
wire   [7:0] tmp_12_fu_420_p4;
wire   [7:0] tmp_4_fu_400_p4;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_451;
reg    ap_condition_455;
reg    ap_condition_125;
reg    ap_condition_234;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 state_V = 4'd0;
#0 first_packet_org_dat = 64'd0;
#0 first_packet_org_las = 1'd0;
#0 first_packet_org_tke = 8'd0;
#0 first_packet_in_data = 64'd0;
#0 second_packet_org_da = 64'd0;
#0 second_packet_org_la = 1'd0;
#0 second_packet_org_tk = 8'd0;
#0 app_packet_out_last_s = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((state_V_load_load_fu_252_p1 == 4'd2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((state_V_load_load_fu_252_p1 == 4'd5) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        app_packet_out_last_s <= first_packet_org_las;
    end else if ((((state_V_load_load_fu_252_p1 == 4'd3) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((state_V_load_load_fu_252_p1 == 4'd6) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        app_packet_out_last_s <= second_packet_org_la;
    end else if ((((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op29_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op13_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        app_packet_out_last_s <= from_eth_V_dout[32'd64];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_125)) begin
        if ((ap_predicate_op61_read_state1 == 1'b1)) begin
                        state_V[0] <= 1'b1;
            state_V[1] <= 1'b0;
            state_V[2] <= 1'b0;
        end else if ((ap_predicate_op44_read_state1 == 1'b1)) begin
                        state_V[2 : 0] <= storemerge3_cast_cas_fu_372_p3[2 : 0];
        end else if ((state_V_load_load_fu_252_p1 == 4'd2)) begin
                        state_V[0] <= 1'b1;
            state_V[1] <= 1'b1;
            state_V[2] <= 1'b0;
        end else if ((state_V_load_load_fu_252_p1 == 4'd3)) begin
                        state_V[0] <= 1'b0;
            state_V[1] <= 1'b0;
            state_V[2] <= 1'b1;
        end else if ((state_V == 4'd4)) begin
                        state_V[2 : 0] <= storemerge1_cast_cas_fu_302_p3[2 : 0];
        end else if ((state_V_load_load_fu_252_p1 == 4'd5)) begin
                        state_V[0] <= 1'b0;
            state_V[1] <= 1'b1;
            state_V[2] <= 1'b1;
        end else if ((state_V_load_load_fu_252_p1 == 4'd6)) begin
                        state_V[0] <= 1'b1;
            state_V[1] <= 1'b1;
            state_V[2] <= 1'b1;
        end else if ((state_V == 4'd7)) begin
                        state_V[2 : 0] <= storemerge_cast_cast_fu_276_p3[2 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op61_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_packet_in_data <= x_V_fu_440_p9;
        first_packet_org_las <= from_eth_V_dout[32'd64];
    end
end

always @ (posedge ap_clk) begin
    if (((state_V_load_reg_550 == 4'd0) & (tmp_reg_583 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_packet_org_dat <= lhs_V_reg_587;
        first_packet_org_tke <= reg_248;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op44_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        lhs_V_1_reg_578 <= lhs_V_1_fu_328_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op61_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        lhs_V_reg_587 <= lhs_V_fu_386_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op29_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op13_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_242 <= from_eth_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op61_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op44_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_248 <= {{from_eth_V_dout[72:65]}};
    end
end

always @ (posedge ap_clk) begin
    if (((state_V_load_reg_550 == 4'd1) & (tmp_1_reg_574 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        second_packet_org_da <= lhs_V_1_reg_578;
        second_packet_org_tk <= reg_248;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op44_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        second_packet_org_la <= from_eth_V_dout[32'd64];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        state_V_load_reg_550[2 : 0] <= state_V[2 : 0];
        tmp_last_V_1_reg_560 <= second_packet_org_la;
        tmp_last_V_reg_554 <= first_packet_org_las;
    end
end

always @ (posedge ap_clk) begin
    if (((state_V == 4'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_1_reg_574 <= from_eth_V_empty_n;
    end
end

always @ (posedge ap_clk) begin
    if (((state_V == 4'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_2_reg_570 <= from_eth_V_empty_n;
    end
end

always @ (posedge ap_clk) begin
    if (((state_V == 4'd7) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_3_reg_566 <= from_eth_V_empty_n;
    end
end

always @ (posedge ap_clk) begin
    if (((state_V == 4'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_reg_583 <= from_eth_V_empty_n;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_451)) begin
        if ((grp_nbreadreq_fu_130_p3 == 1'd0)) begin
            ap_phi_mux_app_packet_out_last_2_phi_fu_170_p4 = app_packet_out_last_s;
        end else if ((grp_nbreadreq_fu_130_p3 == 1'd1)) begin
            ap_phi_mux_app_packet_out_last_2_phi_fu_170_p4 = from_eth_V_dout[32'd64];
        end else begin
            ap_phi_mux_app_packet_out_last_2_phi_fu_170_p4 = ap_phi_reg_pp0_iter0_app_packet_out_last_2_reg_167;
        end
    end else begin
        ap_phi_mux_app_packet_out_last_2_phi_fu_170_p4 = ap_phi_reg_pp0_iter0_app_packet_out_last_2_reg_167;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_455)) begin
        if ((grp_nbreadreq_fu_130_p3 == 1'd0)) begin
            ap_phi_mux_app_packet_out_last_3_phi_fu_161_p4 = app_packet_out_last_s;
        end else if ((grp_nbreadreq_fu_130_p3 == 1'd1)) begin
            ap_phi_mux_app_packet_out_last_3_phi_fu_161_p4 = from_eth_V_dout[32'd64];
        end else begin
            ap_phi_mux_app_packet_out_last_3_phi_fu_161_p4 = ap_phi_reg_pp0_iter0_app_packet_out_last_3_reg_158;
        end
    end else begin
        ap_phi_mux_app_packet_out_last_3_phi_fu_161_p4 = ap_phi_reg_pp0_iter0_app_packet_out_last_3_reg_158;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op61_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op44_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op29_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op13_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        from_eth_V_blk_n = from_eth_V_empty_n;
    end else begin
        from_eth_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op61_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op44_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op29_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op13_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        from_eth_V_read = 1'b1;
    end else begin
        from_eth_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((state_V_load_reg_550 == 4'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((state_V_load_reg_550 == 4'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op94_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        to_pr_V_blk_n = to_pr_V_full_n;
    end else begin
        to_pr_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_234)) begin
        if ((state_V_load_reg_550 == 4'd2)) begin
            to_pr_V_din = tmp_21_fu_518_p4;
        end else if ((state_V_load_reg_550 == 4'd3)) begin
            to_pr_V_din = tmp_37_fu_508_p4;
        end else if ((ap_predicate_op94_write_state2 == 1'b1)) begin
            to_pr_V_din = reg_242;
        end else begin
            to_pr_V_din = 'bx;
        end
    end else begin
        to_pr_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((state_V_load_reg_550 == 4'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((state_V_load_reg_550 == 4'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op94_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        to_pr_V_write = 1'b1;
    end else begin
        to_pr_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((state_V_load_reg_550 == 4'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((state_V_load_reg_550 == 4'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op89_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        to_shell_V_blk_n = to_shell_V_full_n;
    end else begin
        to_shell_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_234)) begin
        if ((state_V_load_reg_550 == 4'd5)) begin
            to_shell_V_din = tmp_6_fu_498_p4;
        end else if ((state_V_load_reg_550 == 4'd6)) begin
            to_shell_V_din = tmp_7_fu_488_p4;
        end else if ((ap_predicate_op89_write_state2 == 1'b1)) begin
            to_shell_V_din = reg_242;
        end else begin
            to_shell_V_din = 'bx;
        end
    end else begin
        to_shell_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((state_V_load_reg_550 == 4'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((state_V_load_reg_550 == 4'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op89_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        to_shell_V_write = 1'b1;
    end else begin
        to_shell_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op61_read_state1 == 1'b1)) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op44_read_state1 == 1'b1)) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op13_read_state1 == 1'b1)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((state_V_load_reg_550 == 4'd2) & (to_pr_V_full_n == 1'b0)) | ((state_V_load_reg_550 == 4'd3) & (to_pr_V_full_n == 1'b0)) | ((to_pr_V_full_n == 1'b0) & (ap_predicate_op94_write_state2 == 1'b1)) | ((state_V_load_reg_550 == 4'd5) & (to_shell_V_full_n == 1'b0)) | ((state_V_load_reg_550 == 4'd6) & (to_shell_V_full_n == 1'b0)) | ((to_shell_V_full_n == 1'b0) & (ap_predicate_op89_write_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op61_read_state1 == 1'b1)) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op44_read_state1 == 1'b1)) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op13_read_state1 == 1'b1)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((state_V_load_reg_550 == 4'd2) & (to_pr_V_full_n == 1'b0)) | ((state_V_load_reg_550 == 4'd3) & (to_pr_V_full_n == 1'b0)) | ((to_pr_V_full_n == 1'b0) & (ap_predicate_op94_write_state2 == 1'b1)) | ((state_V_load_reg_550 == 4'd5) & (to_shell_V_full_n == 1'b0)) | ((state_V_load_reg_550 == 4'd6) & (to_shell_V_full_n == 1'b0)) | ((to_shell_V_full_n == 1'b0) & (ap_predicate_op89_write_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op61_read_state1 == 1'b1)) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op44_read_state1 == 1'b1)) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op13_read_state1 == 1'b1)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((state_V_load_reg_550 == 4'd2) & (to_pr_V_full_n == 1'b0)) | ((state_V_load_reg_550 == 4'd3) & (to_pr_V_full_n == 1'b0)) | ((to_pr_V_full_n == 1'b0) & (ap_predicate_op94_write_state2 == 1'b1)) | ((state_V_load_reg_550 == 4'd5) & (to_shell_V_full_n == 1'b0)) | ((state_V_load_reg_550 == 4'd6) & (to_shell_V_full_n == 1'b0)) | ((to_shell_V_full_n == 1'b0) & (ap_predicate_op89_write_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op61_read_state1 == 1'b1)) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op44_read_state1 == 1'b1)) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((from_eth_V_empty_n == 1'b0) & (ap_predicate_op13_read_state1 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((state_V_load_reg_550 == 4'd2) & (to_pr_V_full_n == 1'b0)) | ((state_V_load_reg_550 == 4'd3) & (to_pr_V_full_n == 1'b0)) | ((to_pr_V_full_n == 1'b0) & (ap_predicate_op94_write_state2 == 1'b1)) | ((state_V_load_reg_550 == 4'd5) & (to_shell_V_full_n == 1'b0)) | ((state_V_load_reg_550 == 4'd6) & (to_shell_V_full_n == 1'b0)) | ((to_shell_V_full_n == 1'b0) & (ap_predicate_op89_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_condition_125 = ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_234 = ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_451 = ((state_V == 4'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_455 = ((state_V == 4'd7) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_app_packet_out_last_2_reg_167 = 'bx;

assign ap_phi_reg_pp0_iter0_app_packet_out_last_3_reg_158 = 'bx;

always @ (*) begin
    ap_predicate_op13_read_state1 = ((grp_nbreadreq_fu_130_p3 == 1'd1) & (state_V == 4'd7));
end

always @ (*) begin
    ap_predicate_op29_read_state1 = ((grp_nbreadreq_fu_130_p3 == 1'd1) & (state_V == 4'd4));
end

always @ (*) begin
    ap_predicate_op44_read_state1 = ((grp_nbreadreq_fu_130_p3 == 1'd1) & (state_V == 4'd1));
end

always @ (*) begin
    ap_predicate_op61_read_state1 = ((grp_nbreadreq_fu_130_p3 == 1'd1) & (state_V == 4'd0));
end

always @ (*) begin
    ap_predicate_op89_write_state2 = ((tmp_3_reg_566 == 1'd1) & (state_V_load_reg_550 == 4'd7));
end

always @ (*) begin
    ap_predicate_op94_write_state2 = ((state_V_load_reg_550 == 4'd4) & (tmp_2_reg_570 == 1'd1));
end

assign grp_fu_212_p4 = {{from_eth_V_dout[15:8]}};

assign grp_fu_222_p4 = {{from_eth_V_dout[23:16]}};

assign grp_fu_232_p4 = {{from_eth_V_dout[31:24]}};

assign grp_nbreadreq_fu_130_p3 = from_eth_V_empty_n;

assign lhs_V_1_fu_328_p1 = from_eth_V_dout[63:0];

assign lhs_V_fu_386_p1 = from_eth_V_dout[63:0];

assign observedAddress_V_fu_346_p6 = {{{{{tmp_20_fu_342_p1}, {tmp_17_fu_338_p1}}, {grp_fu_212_p4}}, {grp_fu_222_p4}}, {grp_fu_232_p4}};

assign state_V_load_load_fu_252_p1 = state_V;

assign storemerge1_cast_cas_fu_302_p3 = ((ap_phi_mux_app_packet_out_last_2_phi_fu_170_p4[0:0] === 1'b1) ? 4'd0 : 4'd4);

assign storemerge3_cast_cas_fu_372_p3 = ((tmp_22_fu_366_p2[0:0] === 1'b1) ? 4'd5 : 4'd2);

assign storemerge_cast_cast_fu_276_p3 = ((ap_phi_mux_app_packet_out_last_3_phi_fu_161_p4[0:0] === 1'b1) ? 4'd0 : 4'd7);

assign tmp_11_fu_410_p4 = {{from_eth_V_dout[39:32]}};

assign tmp_12_fu_420_p4 = {{from_eth_V_dout[55:48]}};

assign tmp_14_fu_430_p4 = {{from_eth_V_dout[47:40]}};

assign tmp_17_fu_338_p1 = from_eth_V_dout[7:0];

assign tmp_20_fu_342_p1 = first_packet_in_data[15:0];

assign tmp_21_fu_518_p4 = {{{first_packet_org_tke}, {tmp_last_V_reg_554}}, {first_packet_org_dat}};

assign tmp_22_fu_366_p2 = (tmp_s_fu_360_p2 | debug_bit_V);

assign tmp_37_fu_508_p4 = {{{second_packet_org_tk}, {tmp_last_V_1_reg_560}}, {second_packet_org_da}};

assign tmp_4_fu_400_p4 = {{from_eth_V_dout[63:56]}};

assign tmp_6_fu_498_p4 = {{{first_packet_org_tke}, {tmp_last_V_reg_554}}, {first_packet_org_dat}};

assign tmp_7_fu_488_p4 = {{{second_packet_org_tk}, {tmp_last_V_1_reg_560}}, {second_packet_org_da}};

assign tmp_8_fu_396_p1 = from_eth_V_dout[7:0];

assign tmp_s_fu_360_p2 = ((observedAddress_V_fu_346_p6 == src_mac_addr_V) ? 1'b1 : 1'b0);

assign x_V_fu_440_p9 = {{{{{{{{tmp_8_fu_396_p1}, {grp_fu_212_p4}}, {grp_fu_222_p4}}, {grp_fu_232_p4}}, {tmp_11_fu_410_p4}}, {tmp_14_fu_430_p4}}, {tmp_12_fu_420_p4}}, {tmp_4_fu_400_p4}};

always @ (posedge ap_clk) begin
    state_V_load_reg_550[3] <= 1'b0;
    state_V[3] <= 1'b0;
end

endmodule //packet_filtering
