-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity packet_filtering is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    from_eth_V_dout : IN STD_LOGIC_VECTOR (72 downto 0);
    from_eth_V_empty_n : IN STD_LOGIC;
    from_eth_V_read : OUT STD_LOGIC;
    to_shell_V_din : OUT STD_LOGIC_VECTOR (72 downto 0);
    to_shell_V_full_n : IN STD_LOGIC;
    to_shell_V_write : OUT STD_LOGIC;
    to_pr_V_din : OUT STD_LOGIC_VECTOR (72 downto 0);
    to_pr_V_full_n : IN STD_LOGIC;
    to_pr_V_write : OUT STD_LOGIC;
    src_mac_addr_V : IN STD_LOGIC_VECTOR (47 downto 0);
    debug_bit_V : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of packet_filtering is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal state_V_load_load_fu_252_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_nbreadreq_fu_130_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op13_read_state1 : BOOLEAN;
    signal ap_predicate_op29_read_state1 : BOOLEAN;
    signal ap_predicate_op44_read_state1 : BOOLEAN;
    signal ap_predicate_op61_read_state1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal state_V_load_reg_550 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_reg_566 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op89_write_state2 : BOOLEAN;
    signal tmp_2_reg_570 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op94_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal state_V : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal first_packet_org_dat : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal first_packet_org_las : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal first_packet_org_tke : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal first_packet_in_data : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal second_packet_org_da : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal second_packet_org_la : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal second_packet_org_tk : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal app_packet_out_last_s : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal from_eth_V_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal to_shell_V_blk_n : STD_LOGIC;
    signal to_pr_V_blk_n : STD_LOGIC;
    signal reg_242 : STD_LOGIC_VECTOR (72 downto 0);
    signal reg_248 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_last_V_reg_554 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_1_reg_560 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_574 : STD_LOGIC_VECTOR (0 downto 0);
    signal lhs_V_1_fu_328_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lhs_V_1_reg_578 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_reg_583 : STD_LOGIC_VECTOR (0 downto 0);
    signal lhs_V_fu_386_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lhs_V_reg_587 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_app_packet_out_last_3_phi_fu_161_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_app_packet_out_last_3_reg_158 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_app_packet_out_last_2_phi_fu_170_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_app_packet_out_last_2_reg_167 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_7_fu_488_p4 : STD_LOGIC_VECTOR (72 downto 0);
    signal tmp_6_fu_498_p4 : STD_LOGIC_VECTOR (72 downto 0);
    signal tmp_37_fu_508_p4 : STD_LOGIC_VECTOR (72 downto 0);
    signal tmp_21_fu_518_p4 : STD_LOGIC_VECTOR (72 downto 0);
    signal storemerge_cast_cast_fu_276_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal storemerge1_cast_cas_fu_302_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal storemerge3_cast_cas_fu_372_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal x_V_fu_440_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_20_fu_342_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_17_fu_338_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_212_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_222_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_232_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal observedAddress_V_fu_346_p6 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_s_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_396_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_fu_410_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_fu_430_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_12_fu_420_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_400_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_451 : BOOLEAN;
    signal ap_condition_455 : BOOLEAN;
    signal ap_condition_125 : BOOLEAN;
    signal ap_condition_234 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    app_packet_out_last_s_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((state_V_load_load_fu_252_p1 = ap_const_lv4_2) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((state_V_load_load_fu_252_p1 = ap_const_lv4_5) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                app_packet_out_last_s <= first_packet_org_las;
            elsif ((((state_V_load_load_fu_252_p1 = ap_const_lv4_3) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((state_V_load_load_fu_252_p1 = ap_const_lv4_6) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                app_packet_out_last_s <= second_packet_org_la;
            elsif ((((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op29_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op13_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                app_packet_out_last_s <= from_eth_V_dout(64 downto 64);
            end if; 
        end if;
    end process;

    state_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_125)) then
                if ((ap_predicate_op61_read_state1 = ap_const_boolean_1)) then 
                    state_V(0) <= '1';
                    state_V(1) <= '0';
                    state_V(2) <= '0';
                elsif ((ap_predicate_op44_read_state1 = ap_const_boolean_1)) then 
                                        state_V(2 downto 0) <= storemerge3_cast_cas_fu_372_p3(2 downto 0);
                elsif ((state_V_load_load_fu_252_p1 = ap_const_lv4_2)) then 
                    state_V(0) <= '1';
                    state_V(1) <= '1';
                    state_V(2) <= '0';
                elsif ((state_V_load_load_fu_252_p1 = ap_const_lv4_3)) then 
                    state_V(0) <= '0';
                    state_V(1) <= '0';
                    state_V(2) <= '1';
                elsif ((state_V = ap_const_lv4_4)) then 
                                        state_V(2 downto 0) <= storemerge1_cast_cas_fu_302_p3(2 downto 0);
                elsif ((state_V_load_load_fu_252_p1 = ap_const_lv4_5)) then 
                    state_V(0) <= '0';
                    state_V(1) <= '1';
                    state_V(2) <= '1';
                elsif ((state_V_load_load_fu_252_p1 = ap_const_lv4_6)) then 
                    state_V(0) <= '1';
                    state_V(1) <= '1';
                    state_V(2) <= '1';
                elsif ((state_V = ap_const_lv4_7)) then 
                                        state_V(2 downto 0) <= storemerge_cast_cast_fu_276_p3(2 downto 0);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op61_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                first_packet_in_data <= x_V_fu_440_p9;
                first_packet_org_las <= from_eth_V_dout(64 downto 64);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_V_load_reg_550 = ap_const_lv4_0) and (tmp_reg_583 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                first_packet_org_dat <= lhs_V_reg_587;
                first_packet_org_tke <= reg_248;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op44_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                lhs_V_1_reg_578 <= lhs_V_1_fu_328_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op61_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                lhs_V_reg_587 <= lhs_V_fu_386_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op29_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op13_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then
                reg_242 <= from_eth_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op61_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op44_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then
                reg_248 <= from_eth_V_dout(72 downto 65);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_V_load_reg_550 = ap_const_lv4_1) and (tmp_1_reg_574 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                second_packet_org_da <= lhs_V_1_reg_578;
                second_packet_org_tk <= reg_248;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op44_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                second_packet_org_la <= from_eth_V_dout(64 downto 64);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                    state_V_load_reg_550(2 downto 0) <= state_V(2 downto 0);
                tmp_last_V_1_reg_560 <= second_packet_org_la;
                tmp_last_V_reg_554 <= first_packet_org_las;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_V = ap_const_lv4_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_1_reg_574 <= (0=>from_eth_V_empty_n, others=>'-');
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_V = ap_const_lv4_4) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_2_reg_570 <= (0=>from_eth_V_empty_n, others=>'-');
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_V = ap_const_lv4_7) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_3_reg_566 <= (0=>from_eth_V_empty_n, others=>'-');
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_V = ap_const_lv4_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_reg_583 <= (0=>from_eth_V_empty_n, others=>'-');
            end if;
        end if;
    end process;
    state_V_load_reg_550(3) <= '0';
    state_V(3) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, from_eth_V_empty_n, ap_predicate_op13_read_state1, ap_predicate_op29_read_state1, ap_predicate_op44_read_state1, ap_predicate_op61_read_state1, to_shell_V_full_n, state_V_load_reg_550, ap_predicate_op89_write_state2, to_pr_V_full_n, ap_predicate_op94_write_state2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op61_read_state1 = ap_const_boolean_1)) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op44_read_state1 = ap_const_boolean_1)) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op29_read_state1 = ap_const_boolean_1)) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op13_read_state1 = ap_const_boolean_1)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((state_V_load_reg_550 = ap_const_lv4_2) and (to_pr_V_full_n = ap_const_logic_0)) or ((state_V_load_reg_550 = ap_const_lv4_3) and (to_pr_V_full_n = ap_const_logic_0)) or ((to_pr_V_full_n = ap_const_logic_0) and (ap_predicate_op94_write_state2 = ap_const_boolean_1)) or ((state_V_load_reg_550 = ap_const_lv4_5) and (to_shell_V_full_n = ap_const_logic_0)) or ((state_V_load_reg_550 = ap_const_lv4_6) and (to_shell_V_full_n = ap_const_logic_0)) or ((to_shell_V_full_n = ap_const_logic_0) and (ap_predicate_op89_write_state2 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, from_eth_V_empty_n, ap_predicate_op13_read_state1, ap_predicate_op29_read_state1, ap_predicate_op44_read_state1, ap_predicate_op61_read_state1, to_shell_V_full_n, state_V_load_reg_550, ap_predicate_op89_write_state2, to_pr_V_full_n, ap_predicate_op94_write_state2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op61_read_state1 = ap_const_boolean_1)) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op44_read_state1 = ap_const_boolean_1)) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op29_read_state1 = ap_const_boolean_1)) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op13_read_state1 = ap_const_boolean_1)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((state_V_load_reg_550 = ap_const_lv4_2) and (to_pr_V_full_n = ap_const_logic_0)) or ((state_V_load_reg_550 = ap_const_lv4_3) and (to_pr_V_full_n = ap_const_logic_0)) or ((to_pr_V_full_n = ap_const_logic_0) and (ap_predicate_op94_write_state2 = ap_const_boolean_1)) or ((state_V_load_reg_550 = ap_const_lv4_5) and (to_shell_V_full_n = ap_const_logic_0)) or ((state_V_load_reg_550 = ap_const_lv4_6) and (to_shell_V_full_n = ap_const_logic_0)) or ((to_shell_V_full_n = ap_const_logic_0) and (ap_predicate_op89_write_state2 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, from_eth_V_empty_n, ap_predicate_op13_read_state1, ap_predicate_op29_read_state1, ap_predicate_op44_read_state1, ap_predicate_op61_read_state1, to_shell_V_full_n, state_V_load_reg_550, ap_predicate_op89_write_state2, to_pr_V_full_n, ap_predicate_op94_write_state2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op61_read_state1 = ap_const_boolean_1)) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op44_read_state1 = ap_const_boolean_1)) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op29_read_state1 = ap_const_boolean_1)) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op13_read_state1 = ap_const_boolean_1)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((state_V_load_reg_550 = ap_const_lv4_2) and (to_pr_V_full_n = ap_const_logic_0)) or ((state_V_load_reg_550 = ap_const_lv4_3) and (to_pr_V_full_n = ap_const_logic_0)) or ((to_pr_V_full_n = ap_const_logic_0) and (ap_predicate_op94_write_state2 = ap_const_boolean_1)) or ((state_V_load_reg_550 = ap_const_lv4_5) and (to_shell_V_full_n = ap_const_logic_0)) or ((state_V_load_reg_550 = ap_const_lv4_6) and (to_shell_V_full_n = ap_const_logic_0)) or ((to_shell_V_full_n = ap_const_logic_0) and (ap_predicate_op89_write_state2 = ap_const_boolean_1)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, ap_done_reg, from_eth_V_empty_n, ap_predicate_op13_read_state1, ap_predicate_op29_read_state1, ap_predicate_op44_read_state1, ap_predicate_op61_read_state1)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op61_read_state1 = ap_const_boolean_1)) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op44_read_state1 = ap_const_boolean_1)) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op29_read_state1 = ap_const_boolean_1)) or ((from_eth_V_empty_n = ap_const_logic_0) and (ap_predicate_op13_read_state1 = ap_const_boolean_1)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(to_shell_V_full_n, state_V_load_reg_550, ap_predicate_op89_write_state2, to_pr_V_full_n, ap_predicate_op94_write_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((state_V_load_reg_550 = ap_const_lv4_2) and (to_pr_V_full_n = ap_const_logic_0)) or ((state_V_load_reg_550 = ap_const_lv4_3) and (to_pr_V_full_n = ap_const_logic_0)) or ((to_pr_V_full_n = ap_const_logic_0) and (ap_predicate_op94_write_state2 = ap_const_boolean_1)) or ((state_V_load_reg_550 = ap_const_lv4_5) and (to_shell_V_full_n = ap_const_logic_0)) or ((state_V_load_reg_550 = ap_const_lv4_6) and (to_shell_V_full_n = ap_const_logic_0)) or ((to_shell_V_full_n = ap_const_logic_0) and (ap_predicate_op89_write_state2 = ap_const_boolean_1)));
    end process;


    ap_condition_125_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_125 <= ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_234_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_234 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_451_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, state_V, ap_block_pp0_stage0)
    begin
                ap_condition_451 <= ((state_V = ap_const_lv4_4) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0));
    end process;


    ap_condition_455_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, state_V, ap_block_pp0_stage0)
    begin
                ap_condition_455 <= ((state_V = ap_const_lv4_7) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_app_packet_out_last_2_phi_fu_170_p4_assign_proc : process(from_eth_V_dout, grp_nbreadreq_fu_130_p3, app_packet_out_last_s, ap_phi_reg_pp0_iter0_app_packet_out_last_2_reg_167, ap_condition_451)
    begin
        if ((ap_const_boolean_1 = ap_condition_451)) then
            if ((grp_nbreadreq_fu_130_p3 = ap_const_lv1_0)) then 
                ap_phi_mux_app_packet_out_last_2_phi_fu_170_p4 <= app_packet_out_last_s;
            elsif ((grp_nbreadreq_fu_130_p3 = ap_const_lv1_1)) then 
                ap_phi_mux_app_packet_out_last_2_phi_fu_170_p4 <= from_eth_V_dout(64 downto 64);
            else 
                ap_phi_mux_app_packet_out_last_2_phi_fu_170_p4 <= ap_phi_reg_pp0_iter0_app_packet_out_last_2_reg_167;
            end if;
        else 
            ap_phi_mux_app_packet_out_last_2_phi_fu_170_p4 <= ap_phi_reg_pp0_iter0_app_packet_out_last_2_reg_167;
        end if; 
    end process;


    ap_phi_mux_app_packet_out_last_3_phi_fu_161_p4_assign_proc : process(from_eth_V_dout, grp_nbreadreq_fu_130_p3, app_packet_out_last_s, ap_phi_reg_pp0_iter0_app_packet_out_last_3_reg_158, ap_condition_455)
    begin
        if ((ap_const_boolean_1 = ap_condition_455)) then
            if ((grp_nbreadreq_fu_130_p3 = ap_const_lv1_0)) then 
                ap_phi_mux_app_packet_out_last_3_phi_fu_161_p4 <= app_packet_out_last_s;
            elsif ((grp_nbreadreq_fu_130_p3 = ap_const_lv1_1)) then 
                ap_phi_mux_app_packet_out_last_3_phi_fu_161_p4 <= from_eth_V_dout(64 downto 64);
            else 
                ap_phi_mux_app_packet_out_last_3_phi_fu_161_p4 <= ap_phi_reg_pp0_iter0_app_packet_out_last_3_reg_158;
            end if;
        else 
            ap_phi_mux_app_packet_out_last_3_phi_fu_161_p4 <= ap_phi_reg_pp0_iter0_app_packet_out_last_3_reg_158;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_app_packet_out_last_2_reg_167 <= "X";
    ap_phi_reg_pp0_iter0_app_packet_out_last_3_reg_158 <= "X";

    ap_predicate_op13_read_state1_assign_proc : process(grp_nbreadreq_fu_130_p3, state_V)
    begin
                ap_predicate_op13_read_state1 <= ((grp_nbreadreq_fu_130_p3 = ap_const_lv1_1) and (state_V = ap_const_lv4_7));
    end process;


    ap_predicate_op29_read_state1_assign_proc : process(grp_nbreadreq_fu_130_p3, state_V)
    begin
                ap_predicate_op29_read_state1 <= ((grp_nbreadreq_fu_130_p3 = ap_const_lv1_1) and (state_V = ap_const_lv4_4));
    end process;


    ap_predicate_op44_read_state1_assign_proc : process(grp_nbreadreq_fu_130_p3, state_V)
    begin
                ap_predicate_op44_read_state1 <= ((grp_nbreadreq_fu_130_p3 = ap_const_lv1_1) and (state_V = ap_const_lv4_1));
    end process;


    ap_predicate_op61_read_state1_assign_proc : process(grp_nbreadreq_fu_130_p3, state_V)
    begin
                ap_predicate_op61_read_state1 <= ((grp_nbreadreq_fu_130_p3 = ap_const_lv1_1) and (state_V = ap_const_lv4_0));
    end process;


    ap_predicate_op89_write_state2_assign_proc : process(state_V_load_reg_550, tmp_3_reg_566)
    begin
                ap_predicate_op89_write_state2 <= ((tmp_3_reg_566 = ap_const_lv1_1) and (state_V_load_reg_550 = ap_const_lv4_7));
    end process;


    ap_predicate_op94_write_state2_assign_proc : process(state_V_load_reg_550, tmp_2_reg_570)
    begin
                ap_predicate_op94_write_state2 <= ((state_V_load_reg_550 = ap_const_lv4_4) and (tmp_2_reg_570 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    from_eth_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, from_eth_V_empty_n, ap_predicate_op13_read_state1, ap_predicate_op29_read_state1, ap_predicate_op44_read_state1, ap_predicate_op61_read_state1, ap_block_pp0_stage0)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op61_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op44_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op29_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op13_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            from_eth_V_blk_n <= from_eth_V_empty_n;
        else 
            from_eth_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    from_eth_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op13_read_state1, ap_predicate_op29_read_state1, ap_predicate_op44_read_state1, ap_predicate_op61_read_state1, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op61_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op44_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op29_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op13_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            from_eth_V_read <= ap_const_logic_1;
        else 
            from_eth_V_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_212_p4 <= from_eth_V_dout(15 downto 8);
    grp_fu_222_p4 <= from_eth_V_dout(23 downto 16);
    grp_fu_232_p4 <= from_eth_V_dout(31 downto 24);
    grp_nbreadreq_fu_130_p3 <= (0=>from_eth_V_empty_n, others=>'-');
    lhs_V_1_fu_328_p1 <= from_eth_V_dout(64 - 1 downto 0);
    lhs_V_fu_386_p1 <= from_eth_V_dout(64 - 1 downto 0);
    observedAddress_V_fu_346_p6 <= ((((tmp_20_fu_342_p1 & tmp_17_fu_338_p1) & grp_fu_212_p4) & grp_fu_222_p4) & grp_fu_232_p4);
    state_V_load_load_fu_252_p1 <= state_V;
    storemerge1_cast_cas_fu_302_p3 <= 
        ap_const_lv4_0 when (ap_phi_mux_app_packet_out_last_2_phi_fu_170_p4(0) = '1') else 
        ap_const_lv4_4;
    storemerge3_cast_cas_fu_372_p3 <= 
        ap_const_lv4_5 when (tmp_22_fu_366_p2(0) = '1') else 
        ap_const_lv4_2;
    storemerge_cast_cast_fu_276_p3 <= 
        ap_const_lv4_0 when (ap_phi_mux_app_packet_out_last_3_phi_fu_161_p4(0) = '1') else 
        ap_const_lv4_7;
    tmp_11_fu_410_p4 <= from_eth_V_dout(39 downto 32);
    tmp_12_fu_420_p4 <= from_eth_V_dout(55 downto 48);
    tmp_14_fu_430_p4 <= from_eth_V_dout(47 downto 40);
    tmp_17_fu_338_p1 <= from_eth_V_dout(8 - 1 downto 0);
    tmp_20_fu_342_p1 <= first_packet_in_data(16 - 1 downto 0);
    tmp_21_fu_518_p4 <= ((first_packet_org_tke & tmp_last_V_reg_554) & first_packet_org_dat);
    tmp_22_fu_366_p2 <= (tmp_s_fu_360_p2 or debug_bit_V);
    tmp_37_fu_508_p4 <= ((second_packet_org_tk & tmp_last_V_1_reg_560) & second_packet_org_da);
    tmp_4_fu_400_p4 <= from_eth_V_dout(63 downto 56);
    tmp_6_fu_498_p4 <= ((first_packet_org_tke & tmp_last_V_reg_554) & first_packet_org_dat);
    tmp_7_fu_488_p4 <= ((second_packet_org_tk & tmp_last_V_1_reg_560) & second_packet_org_da);
    tmp_8_fu_396_p1 <= from_eth_V_dout(8 - 1 downto 0);
    tmp_s_fu_360_p2 <= "1" when (observedAddress_V_fu_346_p6 = src_mac_addr_V) else "0";

    to_pr_V_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_V_load_reg_550, to_pr_V_full_n, ap_predicate_op94_write_state2, ap_block_pp0_stage0)
    begin
        if ((((state_V_load_reg_550 = ap_const_lv4_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((state_V_load_reg_550 = ap_const_lv4_3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op94_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            to_pr_V_blk_n <= to_pr_V_full_n;
        else 
            to_pr_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    to_pr_V_din_assign_proc : process(state_V_load_reg_550, ap_predicate_op94_write_state2, reg_242, tmp_37_fu_508_p4, tmp_21_fu_518_p4, ap_condition_234)
    begin
        if ((ap_const_boolean_1 = ap_condition_234)) then
            if ((state_V_load_reg_550 = ap_const_lv4_2)) then 
                to_pr_V_din <= tmp_21_fu_518_p4;
            elsif ((state_V_load_reg_550 = ap_const_lv4_3)) then 
                to_pr_V_din <= tmp_37_fu_508_p4;
            elsif ((ap_predicate_op94_write_state2 = ap_const_boolean_1)) then 
                to_pr_V_din <= reg_242;
            else 
                to_pr_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            to_pr_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    to_pr_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_V_load_reg_550, ap_predicate_op94_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((state_V_load_reg_550 = ap_const_lv4_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((state_V_load_reg_550 = ap_const_lv4_3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op94_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            to_pr_V_write <= ap_const_logic_1;
        else 
            to_pr_V_write <= ap_const_logic_0;
        end if; 
    end process;


    to_shell_V_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, to_shell_V_full_n, state_V_load_reg_550, ap_predicate_op89_write_state2, ap_block_pp0_stage0)
    begin
        if ((((state_V_load_reg_550 = ap_const_lv4_5) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((state_V_load_reg_550 = ap_const_lv4_6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op89_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            to_shell_V_blk_n <= to_shell_V_full_n;
        else 
            to_shell_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    to_shell_V_din_assign_proc : process(state_V_load_reg_550, ap_predicate_op89_write_state2, reg_242, tmp_7_fu_488_p4, tmp_6_fu_498_p4, ap_condition_234)
    begin
        if ((ap_const_boolean_1 = ap_condition_234)) then
            if ((state_V_load_reg_550 = ap_const_lv4_5)) then 
                to_shell_V_din <= tmp_6_fu_498_p4;
            elsif ((state_V_load_reg_550 = ap_const_lv4_6)) then 
                to_shell_V_din <= tmp_7_fu_488_p4;
            elsif ((ap_predicate_op89_write_state2 = ap_const_boolean_1)) then 
                to_shell_V_din <= reg_242;
            else 
                to_shell_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            to_shell_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    to_shell_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_V_load_reg_550, ap_predicate_op89_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((state_V_load_reg_550 = ap_const_lv4_5) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((state_V_load_reg_550 = ap_const_lv4_6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op89_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            to_shell_V_write <= ap_const_logic_1;
        else 
            to_shell_V_write <= ap_const_logic_0;
        end if; 
    end process;

    x_V_fu_440_p9 <= (((((((tmp_8_fu_396_p1 & grp_fu_212_p4) & grp_fu_222_p4) & grp_fu_232_p4) & tmp_11_fu_410_p4) & tmp_14_fu_430_p4) & tmp_12_fu_420_p4) & tmp_4_fu_400_p4);
end behav;
